/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as systemManagementUsersImport } from './routes/(systemManagement)/users'
import { Route as systemManagementPermissionsImport } from './routes/(systemManagement)/permissions'
import { Route as systemManagementMobileListSystemManagementImport } from './routes/(systemManagement)/mobileListSystemManagement'
import { Route as settingsMobileListSettingsImport } from './routes/(settings)/mobileListSettings'
import { Route as settingsDevicesListImport } from './routes/(settings)/devicesList'
import { Route as settingsDeviceModelsListImport } from './routes/(settings)/deviceModelsList'
import { Route as settingsBanksListImport } from './routes/(settings)/banksList'
import { Route as dashboardErrorsListImport } from './routes/(dashboard)/errorsList'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const systemManagementUsersRoute = systemManagementUsersImport.update({
  id: '/(systemManagement)/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const systemManagementPermissionsRoute =
  systemManagementPermissionsImport.update({
    id: '/(systemManagement)/permissions',
    path: '/permissions',
    getParentRoute: () => rootRoute,
  } as any)

const systemManagementMobileListSystemManagementRoute =
  systemManagementMobileListSystemManagementImport.update({
    id: '/(systemManagement)/mobileListSystemManagement',
    path: '/mobileListSystemManagement',
    getParentRoute: () => rootRoute,
  } as any)

const settingsMobileListSettingsRoute = settingsMobileListSettingsImport.update(
  {
    id: '/(settings)/mobileListSettings',
    path: '/mobileListSettings',
    getParentRoute: () => rootRoute,
  } as any,
)

const settingsDevicesListRoute = settingsDevicesListImport.update({
  id: '/(settings)/devicesList',
  path: '/devicesList',
  getParentRoute: () => rootRoute,
} as any)

const settingsDeviceModelsListRoute = settingsDeviceModelsListImport.update({
  id: '/(settings)/deviceModelsList',
  path: '/deviceModelsList',
  getParentRoute: () => rootRoute,
} as any)

const settingsBanksListRoute = settingsBanksListImport.update({
  id: '/(settings)/banksList',
  path: '/banksList',
  getParentRoute: () => rootRoute,
} as any)

const dashboardErrorsListRoute = dashboardErrorsListImport.update({
  id: '/(dashboard)/errorsList',
  path: '/errorsList',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/errorsList': {
      id: '/(dashboard)/errorsList'
      path: '/errorsList'
      fullPath: '/errorsList'
      preLoaderRoute: typeof dashboardErrorsListImport
      parentRoute: typeof rootRoute
    }
    '/(settings)/banksList': {
      id: '/(settings)/banksList'
      path: '/banksList'
      fullPath: '/banksList'
      preLoaderRoute: typeof settingsBanksListImport
      parentRoute: typeof rootRoute
    }
    '/(settings)/deviceModelsList': {
      id: '/(settings)/deviceModelsList'
      path: '/deviceModelsList'
      fullPath: '/deviceModelsList'
      preLoaderRoute: typeof settingsDeviceModelsListImport
      parentRoute: typeof rootRoute
    }
    '/(settings)/devicesList': {
      id: '/(settings)/devicesList'
      path: '/devicesList'
      fullPath: '/devicesList'
      preLoaderRoute: typeof settingsDevicesListImport
      parentRoute: typeof rootRoute
    }
    '/(settings)/mobileListSettings': {
      id: '/(settings)/mobileListSettings'
      path: '/mobileListSettings'
      fullPath: '/mobileListSettings'
      preLoaderRoute: typeof settingsMobileListSettingsImport
      parentRoute: typeof rootRoute
    }
    '/(systemManagement)/mobileListSystemManagement': {
      id: '/(systemManagement)/mobileListSystemManagement'
      path: '/mobileListSystemManagement'
      fullPath: '/mobileListSystemManagement'
      preLoaderRoute: typeof systemManagementMobileListSystemManagementImport
      parentRoute: typeof rootRoute
    }
    '/(systemManagement)/permissions': {
      id: '/(systemManagement)/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof systemManagementPermissionsImport
      parentRoute: typeof rootRoute
    }
    '/(systemManagement)/users': {
      id: '/(systemManagement)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof systemManagementUsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errorsList': typeof dashboardErrorsListRoute
  '/banksList': typeof settingsBanksListRoute
  '/deviceModelsList': typeof settingsDeviceModelsListRoute
  '/devicesList': typeof settingsDevicesListRoute
  '/mobileListSettings': typeof settingsMobileListSettingsRoute
  '/mobileListSystemManagement': typeof systemManagementMobileListSystemManagementRoute
  '/permissions': typeof systemManagementPermissionsRoute
  '/users': typeof systemManagementUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errorsList': typeof dashboardErrorsListRoute
  '/banksList': typeof settingsBanksListRoute
  '/deviceModelsList': typeof settingsDeviceModelsListRoute
  '/devicesList': typeof settingsDevicesListRoute
  '/mobileListSettings': typeof settingsMobileListSettingsRoute
  '/mobileListSystemManagement': typeof systemManagementMobileListSystemManagementRoute
  '/permissions': typeof systemManagementPermissionsRoute
  '/users': typeof systemManagementUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(dashboard)/errorsList': typeof dashboardErrorsListRoute
  '/(settings)/banksList': typeof settingsBanksListRoute
  '/(settings)/deviceModelsList': typeof settingsDeviceModelsListRoute
  '/(settings)/devicesList': typeof settingsDevicesListRoute
  '/(settings)/mobileListSettings': typeof settingsMobileListSettingsRoute
  '/(systemManagement)/mobileListSystemManagement': typeof systemManagementMobileListSystemManagementRoute
  '/(systemManagement)/permissions': typeof systemManagementPermissionsRoute
  '/(systemManagement)/users': typeof systemManagementUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errorsList'
    | '/banksList'
    | '/deviceModelsList'
    | '/devicesList'
    | '/mobileListSettings'
    | '/mobileListSystemManagement'
    | '/permissions'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errorsList'
    | '/banksList'
    | '/deviceModelsList'
    | '/devicesList'
    | '/mobileListSettings'
    | '/mobileListSystemManagement'
    | '/permissions'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/errorsList'
    | '/(settings)/banksList'
    | '/(settings)/deviceModelsList'
    | '/(settings)/devicesList'
    | '/(settings)/mobileListSettings'
    | '/(systemManagement)/mobileListSystemManagement'
    | '/(systemManagement)/permissions'
    | '/(systemManagement)/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardErrorsListRoute: typeof dashboardErrorsListRoute
  settingsBanksListRoute: typeof settingsBanksListRoute
  settingsDeviceModelsListRoute: typeof settingsDeviceModelsListRoute
  settingsDevicesListRoute: typeof settingsDevicesListRoute
  settingsMobileListSettingsRoute: typeof settingsMobileListSettingsRoute
  systemManagementMobileListSystemManagementRoute: typeof systemManagementMobileListSystemManagementRoute
  systemManagementPermissionsRoute: typeof systemManagementPermissionsRoute
  systemManagementUsersRoute: typeof systemManagementUsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardErrorsListRoute: dashboardErrorsListRoute,
  settingsBanksListRoute: settingsBanksListRoute,
  settingsDeviceModelsListRoute: settingsDeviceModelsListRoute,
  settingsDevicesListRoute: settingsDevicesListRoute,
  settingsMobileListSettingsRoute: settingsMobileListSettingsRoute,
  systemManagementMobileListSystemManagementRoute:
    systemManagementMobileListSystemManagementRoute,
  systemManagementPermissionsRoute: systemManagementPermissionsRoute,
  systemManagementUsersRoute: systemManagementUsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(dashboard)/errorsList",
        "/(settings)/banksList",
        "/(settings)/deviceModelsList",
        "/(settings)/devicesList",
        "/(settings)/mobileListSettings",
        "/(systemManagement)/mobileListSystemManagement",
        "/(systemManagement)/permissions",
        "/(systemManagement)/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(dashboard)/errorsList": {
      "filePath": "(dashboard)/errorsList.tsx"
    },
    "/(settings)/banksList": {
      "filePath": "(settings)/banksList.tsx"
    },
    "/(settings)/deviceModelsList": {
      "filePath": "(settings)/deviceModelsList.tsx"
    },
    "/(settings)/devicesList": {
      "filePath": "(settings)/devicesList.tsx"
    },
    "/(settings)/mobileListSettings": {
      "filePath": "(settings)/mobileListSettings.tsx"
    },
    "/(systemManagement)/mobileListSystemManagement": {
      "filePath": "(systemManagement)/mobileListSystemManagement.tsx"
    },
    "/(systemManagement)/permissions": {
      "filePath": "(systemManagement)/permissions.tsx"
    },
    "/(systemManagement)/users": {
      "filePath": "(systemManagement)/users.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
